export const personDetails = {
    firstName: 'Rich',
    lastName: 'Bell',
    titles: [
        ['🌱', 'Educator'],
        ['💻', 'Programmer'],
        ['🌐', 'Developer'],
        ['🔥', 'Motivator'],
        ['📔', 'Content Creator']
    ],
    bio: 'I am Rich Bell, I am instructor, developer, motivator, and content creator. I love educating people and creating educational materials. In January 2019, I also created a teaching material <b>Javascript for Everyone</b>. In December 2019, I created <b>30 Days of Python</b> challenge and in January 2020 <b>30 Days of JavaScript challenge</b>.',
    keywords: [
        'HTML5',
        'CSS3',
        'JavaScript',
        'Database',
        'React',
        'React Hooks',
        'Context API',
        'React Router',
        'Redux',
        'Node',
        'MongoDB',
        'SQL',
        'API',
        'DOM',
        'data science',
        'MERN',
        'Python',
        'Flask',
        'Statistics',
        'Linear Algebra',
        'Numpy',
        'Pandas',
        'Scipy',
        'Scikit-learn',
        'Visualization',
        'D3.js'
    ],
}
